### ISSUE TITLE
Avoiding wasted render/re-render

### ISSUE THREAD

**Issue by jsphkhan** [ReactTraining/react-media#108]
When using React "Why Did You Update" (why-did-you-update) module to help debug and find wasted renders, I found the Media component to be re-rendering unnecessarily. Has this been brought into notice by anyone earlier. If not, please let me know of any suggestion,

<img width="636" alt="hotels__find_cheap_hotels__hotel_deals__hotel_booking___altayyar_online" src="https://user-images.githubusercontent.com/1991609/48649280-8f07e800-ea0b-11e8-90d4-08063c6f92d7.png">

**Comment by mjackson** [comment]
I'm sorry, but there isn't enough information here to help you. Re-renders could be caused by parent components passing new props. But the only time the state of a `<Media>` component changes is when the state of its media query changes.
