### ISSUE TITLE
React strict mode

### ISSUE THREAD

**Issue by char0n** [ReactTraining/react-media#109]
In [Reacts strict mode](https://reactjs.org/docs/strict-mode.html), react-media is triggering following error when `<MediaQuery>` component is used.

```
Warning: Unsafe lifecycle methods were found within a strict-mode tree:
    in Provider (at index-bundle.js:131)

componentWillMount: Please update the following components to use componentDidMount instead: MediaQuery
```

Would it be possible to comply with the strict mode ?

Thank you

**Comment by edorivai** [comment]
Hi @char0n,

#96 should fix this, you can expect it to be merged soon.
