### ISSUE TITLE
How to check orientation with this?

### ISSUE THREAD

**Issue by sarabs3** [ReactTraining/react-media#117]

**Comment by edorivai** [comment]
This library is just a wrapper around the [`window.matchMedia`](https://developer.mozilla.org/en-US/docs/Web/API/Window/matchMedia) API, meaning you can use any feature supported by media queries.

To answer your question, you could use the [`orientation`](https://developer.mozilla.org/en-US/docs/Web/CSS/@media/orientation) feature:

```jsx
<Media query="(orientation: landscape)">
  {isLandscape =>
    isLandscape
      ? <p>I'm in landscape mode</p>
      : <p>I'm in portait mode</p>
  }
</Media>
```

Disclaimer: I didn't actually run the code above, so please forgive me if there are any typos or anything :sweat_smile:

**Comment by edorivai** [comment]
@sarabs3 I'll consider this solved. Let me know if anything remains unclear!
