### ISSUE TITLE
Problem with SSR + query

### ISSUE THREAD

**Issue by tstirrat15** [ReactTraining/react-media#126]
I've been seeing this error when testing out `next`: 

```
    TypeError: Cannot convert undefined or null to object
        at Function.keys (<anonymous>)
```

I've got a repro in a test, so I'll see what I can do to fix and then push a PR.

**Comment by tstirrat15** [comment]
JK. This is addressed in 11792078661da9219cf7ee5fff25fb0ab4c20225, but that's not released on NPM yet. @edorivai can you release that and I can test it in my project?

**Comment by edorivai** [comment]
Yeah, I'll actually cut a prerelease of v1 now that it should be backwards compatible!

**Comment by edorivai** [comment]
Alright, `react-media@next` should now resolve to `1.10.0-alpha.0`, take a look!
