### ISSUE TITLE
Which browsers are supported?

### ISSUE THREAD

**Issue by devinrhode2** [ReactTraining/react-media#130]
I can't find anything in the readme or issues mentioning anything about which browsers are supported.

I see react-responsive supports IE6+*, but I know react-media uses matchMedia for matching css queries in js - I know matchMedia is supported for IE10 and up. Does react-media simply work wherever matchMedia is defined?

FWIW I only need IE11+ support :)

**Comment by edorivai** [comment]
Yeah, we definitely require `window.matchMedia`. As far as I know, we don't "officially" support any specific browsers, but the source code is really not too complex. So if you find any cross browser bugs, please do let us know :smile:

**Comment by devinrhode2** [comment]
ok cool. For anyone googling, there are polyfills for matchMedia that I
think can give you browser support maybe back to ie6. React-responsive
mentions some polyfills at the end of their Readme, they should work
seamlessly with react-media just like with react-responsive.
