### ISSUE TITLE
DropdownList hover should change rw-state-focus element

### ISSUE THREAD

**Issue by brandoncc** [ReactTraining/react-media#133]
Hi, thanks for this really nice project. I find it very weird that when you open a DropdownList, the first element is always selected (with the obvious border styling by default), and hovering has no effect on it. A traditional select dropdown will let you change the "active" option either with the keyboard or hovering an option, and each continues where the other left off. Your widget considers those two things completely separate.

Is there a reason for this, or was it merely an oversight?

**Comment by brandoncc** [comment]
In the meantime, I did this for anyone else who might have this concern:

```sass
.my-dropdown-parent:hover
    .rw-list-option.rw-state-focus
      border-color: transparent
```

**Comment by edorivai** [comment]
Hi @brandoncc! Are you sure this is the correct repo for posting your issue?

**Comment by brandoncc** [comment]
Ha, not it isn't. I have no idea how I did that. Sorry @edorivai !!
