### ISSUE TITLE
Is height supported?

### ISSUE THREAD

**Issue by Jason-Cooke** [ReactTraining/react-media#142]
I'm trying to mix @media **width** and **height** quries, to get components behaving responsively in all orientations.

Does this module currently support min-height & max-height? If not, are they any plans to add it?

**Comment by edorivai** [comment]
Hi @Jason-Cooke, apologies for the (very) late response. This library is a wrapper around [Window.matchMedia()](https://developer.mozilla.org/en-US/docs/Web/API/Window/matchMedia), which supports any media query features you're familiar with from CSS.
