### ISSUE TITLE
Add hooks to API

### ISSUE THREAD

**Issue by tstirrat15** [ReactTraining/react-media#148]
Opening this issue for tracking purposes.

Things I've figured out so far:

* The notion of a two-pass render is kind of strange the context of hooks. I'm doing my best to approximate it, but it may come at the expense of two `setStates` in the same cycle when it's in frontend-only mode.
* Hooks don't play nicely with the current way that tests are written. I'm going to rewrite the tests to use the React Testing Library.

**Comment by edorivai** [comment]
@tstirrat15 thanks for taking this up man! I currently don't have the time to implement any new stuff so your help is really appreciated!
