### ISSUE TITLE
convert json to media query

### ISSUE THREAD

**Issue by blairanderson** [ReactTraining/react-media#16]
Would you accept a PR that converts JSON input to a media query using something like https://github.com/akiran/json2mq#usage ?

Most notable benefit would be that devs could ignore syntax details of media queries:

before: 
```jsx
const min = 100;
const max = 200;
<Media query={`(min-width: ${min}px) and (max-width: ${max}px)`}>
  foo
</Media>
```

after:
```jsx
const min = 100;
const max = 200;
<Media query={json2mq({minWidth: min, maxWidth: max})}>
foo
</Media>
```

**Comment by mjackson** [comment]
Seems good. I like how `<Media query>` feels a lot like `<div style>` when you can pass an object in. How big is the dep? And is it actively maintained? Looks like the last commit was 2 years ago.

**Comment by mjackson** [comment]
@blairanderson ping

**Comment by mjackson** [comment]
Sure, the project looks good. I'd be happy to accept a PR that uses it.
