### ISSUE TITLE
README Question

### ISSUE THREAD

**Issue by gingur** [ReactTraining/react-media#2]
> If you use a regular React element as children it will be rendered if the query matches. However, you may end up creating a bunch of elements that won't ever actually be rendered to the page (i.e. you'll do a lot of unnecessary createElements on each render). Thus, a children function is the preferred API.

I'm not sure I understand this, the `React.createElement` would only be invoked in the case the condition is truthy.

[Example](http://babeljs.io/repl/#?evaluate=true&lineWrap=false&presets=es2015%2Creact%2Cstage-2&code=const%20React%20%3D%20%7B%20%0A%20%20createElement%3A%20(...args)%20%3D%3E%20%7B%0A%20%20%20%20console.log('in%20createElement'%2C%20...args)%3B%0A%20%20%7D%0A%7D%0A%0Afunction%20Test(%7B%20condition%20%7D)%7B%0A%20%20return%20condition%20%3F%20(%0A%20%20%20%20%3Ch1%3Etrue%3C%2Fh1%3E%0A%20%20%20%20)%20%3A%20(%0A%20%20%20%20%3Ch1%3Efalse%3C%2Fh1%3E%20%20%0A%20%20%20%20)%3B%0A%7D%0ATest(%7B%20condition%3A%20true%20%7D)%3B)

**Comment by mjackson** [comment]
When I say "If you use a regular React element as children" to the `<Media>` component what I mean is this:

```js
<Media query={...}>
  <p>This is a "regular" React element</p>
</Media>
```

When you write code like that, you're creating a bunch of elements that you might not ever need. I'll try to make it clearer in the docs.

**Comment by mjackson** [comment]
I provided some clarification [here](https://github.com/ReactTraining/react-media/commit/9226f859ef3e8092319dd626114730b120dca7e5)

**Comment by gingur** [comment]
Hrmm, I guess I still don't see what perf issue you are trying to solve or the diff between the two.  I've provided another [example](http://babeljs.io/repl/#?evaluate=true&lineWrap=false&presets=es2015%2Creact%2Cstage-2&code=const%20React%20%3D%20%7B%0A%20%20createElement%3A%20(...args)%20%3D%3E%20%7B%0A%20%20%20%20console.log('createElement'%2C%20...args)%0A%20%20%7D%0A%7D%0A%0Afunction%20Conditional(truthy%20%3D%20true)%7B%0A%20%20return%20truthy%20%3F%20(%0A%20%20%20%20%20%20%3Ch1%3Ein%20true%3C%2Fh1%3E%0A%20%20%20%20)%20%3A%20(%0A%20%20%20%20%20%20%3Cnoscript%2F%3E%0A%20%20%20%20)%0A%7D%0A%0Afunction%20ChildrenRender(%7B%20matches%20%3D%20true%2C%20children%20%3D%20Conditional%20%7D%20%3D%20%7B%7D)%7B%0A%20%20return%20children(matches)%0A%7D%0A%0Afunction%20PropRender(%7B%20matches%20%3D%20true%2C%20render%20%3D%20Conditional%20%7D%20%3D%20%7B%7D)%7B%0A%20%20return%20matches%20%3F%20render(matches)%20%3A%20%3Cnoscript%2F%3E%0A%7D%0A%0A%2F%2F%20Child%0AChildrenRender(%7B%20matches%3A%20true%20%7D)%0AChildrenRender(%7B%20matches%3A%20false%20%7D)%0A%0A%2F%2F%20Prop%0APropRender(%7B%20matches%3A%20true%20%7D)%0APropRender(%7B%20matches%3A%20false%20%7D))
