### ISSUE TITLE
Trailing Comma in JSON File Error

### ISSUE THREAD

**Issue by jesskrich** [ReactTraining/react-media#3]
Failed to parse json
npm ERR! Trailing comma in object at 23:3
npm ERR!   },
npm ERR!   ^
npm ERR! File: /Users/jessierichardson/Desktop/new_proj/package.json
npm ERR! Failed to parse package.json data.
npm ERR! package.json must be actual JSON, not just JavaScript.
npm ERR! 
npm ERR! This is not a bug in npm.
npm ERR! Tell the package author to fix their package.json file. JSON.parse

**Comment by mjackson** [comment]
I'm not sure which version you're on but we don't have any trailing commas in our `package.json`.
