### ISSUE TITLE
React rendering failure when trying to use Media component to do anything at all

### ISSUE THREAD

**Issue by TAGC** [ReactTraining/react-media#59]
I'm unable to use Media component to do anything without getting an error like this:

> Invariant Violation: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in. Check the render method of `Temp`.

I also see this warning in the console:

> Warning: React.createElement: type is invalid -- expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in. Check the render method of `Temp`.
>     in Temp (created by DetailPane)
>     in div (created by Panel)
>     in div (created by Panel)
>     in Panel (created by DetailPane)
>     in DetailPane (created by Page)
>     in div (created by Page)
>     in Page (created by Root)
>     in Root
>     in AppContainer

I based Temp on the example component given in the README:

```javascript
class Temp extends React.Component<{}, {}> {
  public render () {
    return (
        <div>
          <Media query={{ maxWidth: 599 }}>
            {(matches) => matches ? (
                <p>The document is less than 600px wide.</p>
            ) : (
                <p>The document is at least 600px wide.</p>
            )}
          </Media>
        </div>
    );
  }
}
```

I then try using this within another React component:

```javascript
  ...
  public render () {
    return (
        <Panel className={`${styles.detailPane}`}>
          <h3>msg1FF</h3>
          {DetailPane.createPropertyRow('Type', 'Tx', true)}
          {DetailPane.createPropertyRow('Template', <FormControl type='text' placeholder='0x FF FF ...'/>)}
          {DetailPane.createPropertyRow('Message ID', <FormControl type='text' placeholder='0x FF ...'/>, true)}
          {DetailPane.createPropertyRow('Repeat rate', <FormControl type='number'/>, true)}
          <hr/>
          <Temp/>
          <h4>Fields</h4>
          <BootstrapTable striped hover data={fields}>
            <TableHeaderColumn isKey dataField='name'>Name</TableHeaderColumn>
            <TableHeaderColumn dataField='type' width='25%'>Type</TableHeaderColumn>
            <TableHeaderColumn dataField='startBit' width='12%'>Start Bit</TableHeaderColumn>
            <TableHeaderColumn dataField='size' width='10%'>Size</TableHeaderColumn>
            <TableHeaderColumn dataField='endianness' width='15%'>Endianness</TableHeaderColumn>
            <TableHeaderColumn dataFormat={DetailPane.optionsFormatter} width='60'/>
          </BootstrapTable>
        </Panel>
    );
  }
```

**Comment by TAGC** [comment]
For the record, I've just tried something very similar with [react-responsive](https://github.com/contra/react-responsive) and the same issue occurs.

**Comment by TAGC** [comment]
I've discovered the issue; I need to use `import * as Media from 'react-media';` instead of `import Media from 'react-media'` (and ditto with react-responsive).

I'm not sure why this is as you're clearly exporting `Media` as the default export in your source code. The former should work as well. Might be a transpiling issue on my end.

**Comment by mjackson** [comment]
Yep, sounds like you've got an issue with your compilation step. Good luck!

**Comment by dakotamurphyucf** [comment]
Just in case someone comes by this and uses cjs imports and gets this. Try 
``const Media = require('react-media').default;``

**Comment by bjolseth** [comment]
I think this should be re-opened. I had exactly the same problem. Vanilla react project using parcel builder. never any problems with other packages. Solution with .default worked.
At the very least, add it as a tip to the README file? Bad not to have a working hello world example with a 'non-custom' builder
