### ISSUE TITLE
Server side render warning

### ISSUE THREAD

**Issue by saniko** [ReactTraining/react-media#64]
HI,
Got the "Warning: React attempted to reuse markup..." message.
Following issue [13](https://github.com/ReactTraining/react-media/issues/13) and [46](https://github.com/ReactTraining/react-media/issues/46), I don't understand whats is the preferred way to solve this.

Could someone please clarify. 

Best.

**Comment by bouzlibop** [comment]
@saniko If I'm not mistaken the warning message will disappear as soon as new version is released (see also https://github.com/ReactTraining/react-media/issues/68).

**Comment by bouzlibop** [comment]
@mjackson would you be able to release new version this week? 🙏

**Comment by mjackson** [comment]
@bouzlibop Done! Just released version 1.6.0 https://github.com/ReactTraining/react-media/releases/tag/v1.6.0
