### ISSUE TITLE
Prop `query` is required even if I use `queries`

### ISSUE THREAD

**Issue by deiucanta** [ReactTraining/react-media#65]
```
<Media queries={{
  small: { maxWidth: 991 },
  medium: { minWidth: 992, maxWidth: 1199 },
  large: { minWidth: 1200 },
}}>
  {(small, medium, large) => {
    if (small) return S
    if (medium) return M
    if (large) return L
  }}
</Media>
```

```
Failed prop type: The prop `query` is marked as required in `Media`, but its value is `undefined`.
```

**Comment by gribnoysup** [comment]
I'm getting the same "issue" here, but it seems that the problem is not in required `query` prop. Seems like `queries` API wasn't published yet, so if you install this module via npm right now, you will get the version without queries

**Comment by alanhussey** [comment]
Ah, that makes sense. Looks like [`1.5.1`](https://github.com/ReactTraining/react-media/blob/v1.5.1/modules/Media.js) doesn't have any support for `queries`.

**Comment by cherihung** [comment]
when will there be another release to include the current code supporting 'queries' ?

**Comment by mjackson** [comment]
You're trying to use a feature that hasn't been released yet. It'll be there in the next major version.
