### ISSUE TITLE
Possible use case?

### ISSUE THREAD

**Issue by timarney** [ReactTraining/react-media#7]
Love how small the footprint is for this.

Not sure if this makes sense but wondering if this lib could be used to set variables outside of the render method for other uses.

Example I'm messing around with react-virtualized 
```
<VirtualScroll
    ...
    rowHeight={110}
 />
```

Based on the width of the screen I know what the height of my rows will be.

(max-width: 480px) set the variable to be X else set to Y

**Comment by mjackson** [comment]
You mean like this?

```js
<Media query="(max-width: 480px)">
{matches => matches ? (
  <VirtualScroll rowHeight={X}/>
) : (
  <VirtualScroll rowHeight={Y}/>
)/>
```

**Comment by timarney** [comment]
Ya but I was hoping not to dup the whole Component - just need to flip 1 prop / num (rowHeight)

```
<VirtualScroll
                      autoHeight
                      className='VirtualScroll'
                      height={height}
                      rowCount={list.size}
                      rowHeight={110}
                      rowClassName='therow'
                      rowRenderer={({ index }) => this._rowRenderer({ index })}
                      scrollTop={scrollTop}
                      width={width}
                    />
```

**Comment by mjackson** [comment]
It's just JavaScript ;) You can re-arrange the logic however you want.

```js
<Media query="(max-width: 480px)">
{matches => {
  const rowHeight = matches ? X : Y

  return (
    <VirtualScroll rowHeight={rowHeight} .../>
  )
}
/>
```

**Comment by timarney** [comment]
Nice thanks - ha seeing it in a format other than the ternary makes more sense to me now.

**Comment by mjackson** [comment]
Ya those inline ternaries always throw me too :) Probably should've broken it out to begin with.

**Comment by timarney** [comment]
Man I got some sleep and realized how powerful this is - what it can do.  

Not just hiding stuff on the page like http://foundation.zurb.com/sites/docs/v/5.5.3/components/visibility.html 

Best part - It's just JavaScript ;)

This just showed up in my feed https://github.com/nygardk/react-break might kick up some ideas for https://github.com/ReactTraining/react-media/issues/5

**Comment by timarney** [comment]
FYI - works great https://twitter.com/timarney/status/767031104452853760 (WIP)
