### ISSUE TITLE
Publish v1.7.0 to npm 🚀

### ISSUE THREAD

**Issue by yamafaktory** [ReactTraining/react-media#82]
Hi!

The latest release has not been published yet to npm https://github.com/ReactTraining/react-media/blob/master/package.json#L3.

Thanks!

**Comment by yamafaktory** [comment]
Sorry for the convenience, I'll self-close it as this has been already discussed in #79.

**Comment by mjackson** [comment]
@yamafaktory I'm planning on releasing 1.7 later today. Thanks for the nudge ;)

**Comment by mjackson** [comment]
I just [released 1.8.0-rc.1](https://github.com/ReactTraining/react-media/releases/tag/v1.8.0-rc.1). Please give it a shot and let me know how it goes!

```sh
npm install react-media@next
```
