### ISSUE TITLE
error when using enzyme mount

### ISSUE THREAD

**Issue by abdellah-el-mennani** [ReactTraining/react-media#86]
Sorry for my English,
I tried to test a component that uses Media component using enzyme and jest but I got this error:
```
<Media targetWindow> does not support `matchMedia`
```
I use mount from enzyme.

**Comment by RusinovAnton** [comment]
I've just fixed my tests by adding mock for `window.matchMedia` API in the setup file of jest tests.  
I assume it could be added in the `beforeAll` or `before` hooks also if needed.

```es6
window.matchMedia = () => ({ 
  addListener: () => {}, 
  removeListener: () => {} 
});
```

**Comment by abdellah-el-mennani** [comment]
Thank you a lot @RusinovAnton , the trick works
