### ISSUE TITLE
media query changes in file require a full browser refresh when using react-hot-loader

### ISSUE THREAD

**Issue by CallidusAsinus** [ReactTraining/react-media#87]
When I make a change such as ```<Media query="(min-width: 1120px)">``` to ```<Media query="(min-width: 900px)">```, I need to refresh my browser in order for the change to take effect.

react version: 16.2.0
react-hot-loader version: 4.0.1
react-media version: 1.8.0
webpack-dev-server version: 3.1.1

**Comment by edorivai** [comment]
I guess it would be good to take prop changes of `query` into account.

I don't know whether it's a good idea, but I guess dynamically updating a media query wouldn't work right now.

**Comment by edorivai** [comment]
@CallidusAsinus I'm most probably missing something here, as I tried reproducing the bug, but couldn't manage.

I've quickly setup hot reloading in an ejected `create-react-app`-app, and tried to mirror your package versions. Only thing I couldn't manage was to get CRA working with `webpack-dev-server@3`, it comes with version 2.x.

I've published the setup here: https://github.com/edorivai/react-media-hotloader

@theKashey any idea why this is working for me? :sweat_smile: 

![peek 2018-08-31 09-19](https://user-images.githubusercontent.com/765358/44898380-0c6e6700-acff-11e8-843c-1077db415b92.gif)

**Comment by theKashey** [comment]
@edorivai - `modules.hot` and `react-hot-loader` are a bit different.
In your case you are _hot_ reloading your application, remounting all the components
With RHL - you will _hot_ update existing components.

The only way to fix this - handle query prop change in `componentDidUpdate()`

**Comment by edorivai** [comment]
Hmmmm, I used the ["Migrating from create-react-app"](https://github.com/gaearon/react-hot-loader#migrating-from-create-react-app) recipe as outlined in the `react-hot-loader` docs. And the end result seems very similar to the ["Getting started"](https://github.com/gaearon/react-hot-loader#getting-started) flow.

> With RHL - you will hot update existing components.

How do I get this :point_up: ? :sweat_smile:

**Comment by edorivai** [comment]
@CallidusAsinus If this is still an issue for you, I would really appreciate a reproduction repo to take a look at. You could even fork and edit [my failed attempt](https://github.com/edorivai/react-media-hotloader) at reproducing this.

**Comment by theKashey** [comment]
> With RHL - you will hot update existing components.

(🐢 mode), as long as idea around Hot Loader is to change your code without changing your state - that is what you will get using React-Hot-Loader. But it could be tricky to setup it with CRA.

**Comment by edorivai** [comment]
I'm going to close this for now. If this issue is still important for someone, then please ping me in this issue, and add a codesandbox reproduction case to your reopen request.
