### ISSUE TITLE
onChange callback is not triggered

### ISSUE THREAD

**Issue by timkraut** [ReactTraining/react-media#99]
Hi,

I've been struggling with the `onChange` callback. The break point detection works fine but the function I pass to `onChange` is never called.

I use the following code:
```js
function logOnChange() {
  console.log("changed");
}

function App() {
  return (
    <Media query={{ maxWidth: 500 }} onChange={logOnChange}>
      {matches => (matches ? <p>Small</p> : <p>Large</p>)}
    </Media>
  );
}
```

I've created a Codesandbox to illustrate the issue:
https://codesandbox.io/s/5v82oypykl

Am I doing something wrong or is this broken?

Thanks in advance!

**Comment by edorivai** [comment]
Hey, the current changes in master haven't been deployed to npm yet. Feel free to follow #98 for progress updates.

**Comment by ImHamzaAnwer** [comment]
I am facing the same issue
